<a href="https://colab.research.google.com/github/yenlung/Python-Book/blob/master/%E5%86%92%E9%9A%AA29_%E6%AD%A1%E8%BF%8E%E4%BE%86%E5%88%B0%20Array%20%E7%9A%84%E4%B8%96%E7%95%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

貓貓大學數學系剛結束期末考，微積分老師立刻把考卷改完，八位同學的成績是這樣的：

A同學：35分、B同學：74分、C同學：43分、D同學：66分、
E同學：87分、F同學：55分、G同學：71分、H同學：65分

現在老師決定讓每位同學的成績都乘上1.1倍來調整分數，這時能怎麼做呢？

用一個串列記錄八位同學的成績。

In [ ]:
grades = [35, 74, 43, 66, 87, 55, 71, 65]

In [ ]:
grades*1.1

TypeError: can't multiply sequence by non-int of type 'float'

出現Error了，就是說不能乘「非整數」1.1的意思，那試試看乘以2倍。

In [ ]:
grades*2

[35, 74, 43, 66, 87, 55, 71, 65, 35, 74, 43, 66, 87, 55, 71, 65]

哦…好像可以了？！但是串列的乘法不是真的在計算，而是讓串列中的東西重複出現。

換個方法就可以。

In [ ]:
new_grades = []

for g in grades:
    new_grades.append(g*1.1)

In [ ]:
new_grades

[38.5,
 81.4,
 47.300000000000004,
 72.60000000000001,
 95.7,
 60.50000000000001,
 78.10000000000001,
 71.5]

假設老師決定每位同學的成績再加4分，該怎麼做呢？

In [ ]:
new_grades2 = []

for g in new_grades:
    new_grades2.append(g+4)

In [ ]:
new_grades2

[42.5,
 85.4,
 51.300000000000004,
 76.60000000000001,
 99.7,
 64.5,
 82.10000000000001,
 75.5]

有沒有更快的方法呢？

In [ ]:
grad_arr = np.array(grades)

In [ ]:
grad_arr

array([35, 74, 43, 66, 87, 55, 71, 65])

In [ ]:
grad_arr * 1.1

array([38.5, 81.4, 47.3, 72.6, 95.7, 60.5, 78.1, 71.5])

In [ ]:
grad_arr * 1.1 + 4

array([42.5, 85.4, 51.3, 76.6, 99.7, 64.5, 82.1, 75.5])