In [ ]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

我們之前「一次調分」神技，其實是用了 Broadcasting 廣播的功能！

現在來複習一下，狀況弄簡單一點。有一位同學的成績是這樣：平時成績85分、期中考70分、期末考80分。

In [2]:
grades = np.array([85, 70, 80])

如果平時、期中、期末的成績都要乘以 1.1倍。那就讓1.1「廣播」到每一個分數，然後相乘。

In [3]:
grades * 1.1

array([93.5, 77. , 88. ])

我們想幫這位同學算學期成績，但學期成績滿分就是100分，如果直接將上面三個分數加起來就超過了。

所以學期成績通常有一個加權方式，像是平時成績佔20%、期中考佔35%、期末考佔45%。

In [4]:
weights = np.array([0.2, 0.35, 0.45])

平時、期中、期末加權成績。

In [5]:
wgrades = grades * weights

In [6]:
wgrades

array([17. , 24.5, 36. ])

把每項成績加起來，得到最後的學期成績。

In [7]:
wgrades.sum()

77.5

更快的方法——內積。

In [9]:
np.dot(grades, weights)

77.5

In [10]:
grades @ weights

77.5

同時算三位同學的學期成績。

In [11]:
grades = np.array([[85, 70, 80],
                 [12, 88, 77],
                 [85, 91, 33]])

In [12]:
weights = np.array([0.2, 0.35, 0.45])

In [13]:
grades @ weights

array([77.5 , 67.85, 63.7 ])

array 的不同形狀。

一維向量

In [14]:
np.array([0, 1, 2])

array([0, 1, 2])

二維矩陣

In [15]:
np.array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

三維 array

In [16]:
np.array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],
        [[3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]]])

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]]])