<a href="https://colab.research.google.com/github/yenlung/Python-Book/blob/master/%E5%86%92%E9%9A%AA31_Array%20%E5%A4%A7%E8%AE%8A%E8%BA%AB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

用亂數取一個 array，總共有100個數字，從標準常態分配取出來。

In [ ]:
A = np.random.randn(100)

In [ ]:
A

array([-2.72697506, -0.48058   , -0.15574267, -0.13942442, -0.3376635 ,
       -0.29167009,  1.61485719,  0.62831549, -1.14209909,  1.68243169,
        0.05528804, -1.10391534, -0.56509848,  1.27057431, -0.58304805,
       -0.47687213,  0.52477164, -0.05921194,  0.0158503 ,  0.24500786,
        0.50065152, -0.07975364,  0.04423025, -1.64426951,  1.02096193,
        0.97048843, -0.23400202,  0.222815  ,  1.07846767,  0.37421148,
       -1.8667843 ,  1.38720049, -0.84074182, -2.13774315, -0.85085162,
       -0.0783195 , -1.49767334, -0.47644988,  0.38384577, -0.29615875,
        0.65788933,  0.52978153, -0.85176102,  1.02751439, -0.42419701,
        0.2820004 , -0.85960879, -0.75398854,  1.59870293, -0.82430129,
        1.83765512, -1.55907902,  2.4500909 ,  0.23016465, -0.50349978,
       -0.75510116, -0.42588214, -0.2192467 ,  2.00255091,  0.1988972 ,
        0.61926882, -0.07898414,  0.2758582 , -1.0873957 , -0.47862835,
        0.4596482 ,  1.59304573, -0.43175379,  1.21842128,  0.92

A 目前的形狀。

In [ ]:
A.shape

(100,)

把 A 變成 5$\times$20 的矩陣。

In [ ]:
A.shape = (5, 20)

In [ ]:
A

array([[-2.72697506, -0.48058   , -0.15574267, -0.13942442, -0.3376635 ,
        -0.29167009,  1.61485719,  0.62831549, -1.14209909,  1.68243169,
         0.05528804, -1.10391534, -0.56509848,  1.27057431, -0.58304805,
        -0.47687213,  0.52477164, -0.05921194,  0.0158503 ,  0.24500786],
       [ 0.50065152, -0.07975364,  0.04423025, -1.64426951,  1.02096193,
         0.97048843, -0.23400202,  0.222815  ,  1.07846767,  0.37421148,
        -1.8667843 ,  1.38720049, -0.84074182, -2.13774315, -0.85085162,
        -0.0783195 , -1.49767334, -0.47644988,  0.38384577, -0.29615875],
       [ 0.65788933,  0.52978153, -0.85176102,  1.02751439, -0.42419701,
         0.2820004 , -0.85960879, -0.75398854,  1.59870293, -0.82430129,
         1.83765512, -1.55907902,  2.4500909 ,  0.23016465, -0.50349978,
        -0.75510116, -0.42588214, -0.2192467 ,  2.00255091,  0.1988972 ],
       [ 0.61926882, -0.07898414,  0.2758582 , -1.0873957 , -0.47862835,
         0.4596482 ,  1.59304573, -0.43175379,  

要改變array的形狀還可以這樣，這次我們想換成100$\times$1的矩陣。

In [ ]:
A.reshape(100, 1)

array([[-2.72697506],
       [-0.48058   ],
       [-0.15574267],
       [-0.13942442],
       [-0.3376635 ],
       [-0.29167009],
       [ 1.61485719],
       [ 0.62831549],
       [-1.14209909],
       [ 1.68243169],
       [ 0.05528804],
       [-1.10391534],
       [-0.56509848],
       [ 1.27057431],
       [-0.58304805],
       [-0.47687213],
       [ 0.52477164],
       [-0.05921194],
       [ 0.0158503 ],
       [ 0.24500786],
       [ 0.50065152],
       [-0.07975364],
       [ 0.04423025],
       [-1.64426951],
       [ 1.02096193],
       [ 0.97048843],
       [-0.23400202],
       [ 0.222815  ],
       [ 1.07846767],
       [ 0.37421148],
       [-1.8667843 ],
       [ 1.38720049],
       [-0.84074182],
       [-2.13774315],
       [-0.85085162],
       [-0.0783195 ],
       [-1.49767334],
       [-0.47644988],
       [ 0.38384577],
       [-0.29615875],
       [ 0.65788933],
       [ 0.52978153],
       [-0.85176102],
       [ 1.02751439],
       [-0.42419701],
       [ 0

reshape 後形狀沒有改變。

In [ ]:
A.shape

(5, 20)

賦值才能改變形狀。

In [ ]:
A = A.reshape(100, 1)
A.shape

(100, 1)