In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

生成 array 的標準方法。

先生成一個 list。

In [2]:
xy = [[x, y] for x in range(5) for y in range(3)]

In [3]:
xy

[[0, 0],
 [0, 1],
 [0, 2],
 [1, 0],
 [1, 1],
 [1, 2],
 [2, 0],
 [2, 1],
 [2, 2],
 [3, 0],
 [3, 1],
 [3, 2],
 [4, 0],
 [4, 1],
 [4, 2]]

用 array 包起來。

In [4]:
xy = np.array(xy)

生成特殊的 array。

零向量

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

零矩陣

In [6]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

單位矩陣

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])