<a href="https://colab.research.google.com/github/yenlung/Python-Book/blob/master/%E5%86%92%E9%9A%AA30_Broadcasting%20%E6%AF%94%E6%88%91%E5%80%91%E6%83%B3%E5%83%8F%E6%9B%B4%E6%9C%89%E8%B6%A3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

我們之前「一次調分」神技，其實是用了 Broadcasting 廣播的功能！

現在來複習一下，狀況弄簡單一點。有一位同學的成績是這樣：平時成績85分、期中考70分、期末考80分。

In [ ]:
grades = np.array([85, 70, 80])

如果平時、期中、期末的成績都要乘以 1.1倍。那就讓1.1「廣播」到每一個分數，然後相乘。

In [ ]:
grades * 1.1

array([93.5, 77. , 88. ])

我們想幫這位同學算學期成績，但學期成績滿分就是100分，如果直接將上面三個分數加起來就超過了。

所以學期成績通常有一個加權方式，像是平時成績佔20%、期中考佔35%、期末考佔45%。

In [ ]:
weights = np.array([0.2, 0.35, 0.45])

平時、期中、期末加權成績。

In [ ]:
wgrades = grades * weights

In [ ]:
wgrades

array([17. , 24.5, 36. ])

把每項成績加起來，得到最後的學期成績。

In [ ]:
wgrades.sum()

77.5

更快的方法——內積。

In [ ]:
np.dot(grades, weights)

77.5

In [ ]:
grades @ weights

77.5

同時算三位同學的學期成績。

In [ ]:
grades = np.array([[85, 70, 80],
                 [12, 88, 77],
                 [85, 91, 33]])

In [ ]:
weights = np.array([0.2, 0.35, 0.45])

In [ ]:
grades @ weights

array([77.5 , 67.85, 63.7 ])

array 的不同形狀。

一維向量

In [ ]:
np.array([0, 1, 2])

array([0, 1, 2])

二維矩陣

In [ ]:
np.array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

三維 array

In [ ]:
np.array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],
        [[3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]]])

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]]])